---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u0715251/public_html/web_testing
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R page $DEPLOYPATH
    - /bin/cp -R res $DEPLOYPATH
    - /bin/cp -R script $DEPLOYPATH
    - /bin/cp -R style $DEPLOYPATH
